# NAME: Stephanie Doan
# EMAIL: stephaniekdoan@ucla.edu
# ID: 604981556

default:
	gcc -g -Wall -Wextra lab1a.c -o lab1a

clean: 
	rm -f lab1a *.tar.gz

dist:
	tar -cvzf lab1a-604981556.tar.gz lab1a.c Makefile README
