# NAME: Ashley Zhu, Stephanie Doan
# EMAIL: ashleytz@g.ucla.edu, stephaniekdoan@ucla.edu
# ID: 505308582, 604981556

default:
	g++ -Wall -Wextra lab3a.cpp -o lab3a

dist:
	tar -cvzf lab3a-604981556.tar.gz lab3a.cpp ext2_fs.h Makefile README

clean:
	rm -f lab3a  *.tar.gz
